# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(545, 420)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 411, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrower = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrower.setObjectName("textBrower")
        self.verticalLayout.addWidget(self.textBrower)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.but_start = QtWidgets.QPushButton(self.layoutWidget)
        self.but_start.setObjectName("but_start")
        self.horizontalLayout.addWidget(self.but_start)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.but_pause = QtWidgets.QPushButton(self.layoutWidget)
        self.but_pause.setObjectName("but_pause")
        self.horizontalLayout.addWidget(self.but_pause)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.but_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.but_stop.setObjectName("but_stop")
        self.horizontalLayout.addWidget(self.but_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.but_start.clicked.connect(Form.monitor_start) # type: ignore
        self.but_stop.clicked.connect(Form.monitor_stop) # type: ignore
        self.but_pause.clicked.connect(Form.monitor_pause) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.but_start.setText(_translate("Form", "start"))
        self.but_pause.setText(_translate("Form", "pause"))
        self.but_stop.setText(_translate("Form", "stop"))
